// Generated from src/template-build/modules. Do not edit this file directly.

// ../../AppData/Roaming/npm/node_modules/create-sjmcl-extension/src/template-build/modules/index.js
import { build } from "esbuild";
import { zipSync } from "fflate";
import semver from "semver";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import path3 from "node:path";
import { fileURLToPath } from "node:url";

// ../../AppData/Roaming/npm/node_modules/create-sjmcl-extension/src/template-build/modules/constants.js
var IDENTIFIER_PATTERN = /^[a-z][a-z0-9_-]*(\.[a-z][a-z0-9_-]*)+$/;
var RESET = "\x1B[0m";
var BOLD = "\x1B[1m";
var YELLOW = "\x1B[33m";
var FORBIDDEN_IMPORT_TARGETS = /* @__PURE__ */ new Map([
  ["react", "api.React"],
  ["@chakra-ui/react", "api.ChakraUI"]
]);
var HOST_SINGLETON_PACKAGES = [
  { packageName: "react", replacement: "api.React" },
  { packageName: "@chakra-ui/react", replacement: "api.ChakraUI" }
];
var HOST_PROVIDED_SINGLETON_DOCS = "https://mc.sjtu.cn/sjmcl/en/dev/extension/api.html#injected-objects";
var JSX_PATTERN = /<\/?[A-Za-z][\w.:+-]*(?:\s[^<>]*?)?>|<>|<\/>/m;

// ../../AppData/Roaming/npm/node_modules/create-sjmcl-extension/src/template-build/modules/utils.js
function supportsColor(stream) {
  return Boolean(stream?.isTTY) && process.env.NO_COLOR === void 0 && process.env.TERM !== "dumb";
}
function formatWarningLabel() {
  if (!supportsColor(process.stderr)) {
    return "WARNING";
  }
  return `${BOLD}${YELLOW}WARNING${RESET}`;
}
function normalizeRelativePath(value) {
  return String(value || "").replace(/\\/g, "/").trim();
}
function escapeRegExp(value) {
  return String(value || "").replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function isNodeModulesPath(filePath) {
  return /(^|\/)node_modules\//.test(normalizeRelativePath(filePath));
}
function validateRelativePackagePath(value, fieldName) {
  const normalized = normalizeRelativePath(value);
  if (!normalized) {
    throw new Error(`${fieldName} is required.`);
  }
  if (normalized.startsWith("/") || normalized.startsWith("../")) {
    throw new Error(`${fieldName} must stay inside the extension package.`);
  }
  if (normalized.split("/").some((segment) => segment === "" || segment === "..")) {
    throw new Error(`${fieldName} must be a normalized relative path.`);
  }
  if (!normalized.endsWith(".js")) {
    throw new Error(`${fieldName} must point to a .js file.`);
  }
  return normalized;
}

// ../../AppData/Roaming/npm/node_modules/create-sjmcl-extension/src/template-build/modules/project-files.js
import { cpSync, existsSync, readFileSync, readdirSync } from "node:fs";
import path from "node:path";
function readJson(filePath) {
  return JSON.parse(readFileSync(filePath, "utf8"));
}
function copyIfExists(sourcePath, targetPath) {
  if (!existsSync(sourcePath)) {
    return;
  }
  cpSync(sourcePath, targetPath, { recursive: true });
}
function addDirectoryToZipTree(sourceDirectory) {
  const currentNode = {};
  for (const entry of readdirSync(sourceDirectory, { withFileTypes: true })) {
    const sourcePath = path.join(sourceDirectory, entry.name);
    if (entry.isDirectory()) {
      currentNode[entry.name] = addDirectoryToZipTree(sourcePath);
      continue;
    }
    currentNode[entry.name] = readFileSync(sourcePath);
  }
  return currentNode;
}
function resolveSourceEntryPath(projectRoot2) {
  const candidates = [
    path.join(projectRoot2, "src", "index.ts"),
    path.join(projectRoot2, "src", "index.tsx")
  ];
  const existingCandidates = candidates.filter((candidate) => existsSync(candidate));
  if (existingCandidates.length === 0) {
    throw new Error("Expected src/index.ts or src/index.tsx.");
  }
  if (existingCandidates.length > 1) {
    console.warn(
      `${formatWarningLabel()} Both src/index.ts and src/index.tsx exist; using src/index.ts.`
    );
  }
  return existingCandidates[0];
}
function collectSourceFiles(rootDirectory) {
  const files = [];
  for (const entry of readdirSync(rootDirectory, { withFileTypes: true })) {
    const entryPath = path.join(rootDirectory, entry.name);
    if (entry.isDirectory()) {
      files.push(...collectSourceFiles(entryPath));
      continue;
    }
    if (/\.(tsx?|jsx?)$/.test(entry.name)) {
      files.push(entryPath);
    }
  }
  return files;
}
function toProjectRelativePath(projectRoot2, sourcePath) {
  return normalizeRelativePath(path.relative(projectRoot2, sourcePath));
}

// ../../AppData/Roaming/npm/node_modules/create-sjmcl-extension/src/template-build/modules/source-analysis.js
import { existsSync as existsSync2, readFileSync as readFileSync2 } from "node:fs";
import path2 from "node:path";
function getForbiddenImportCounts(content) {
  const importMatches = content.matchAll(
    /^\s*import(?:["'\s\S]*?\sfrom\s*)?["']([^"']+)["'];?/gm
  );
  const importCounts = /* @__PURE__ */ new Map();
  for (const match of importMatches) {
    const packageName = match[1];
    if (!FORBIDDEN_IMPORT_TARGETS.has(packageName)) {
      continue;
    }
    importCounts.set(packageName, (importCounts.get(packageName) || 0) + 1);
  }
  return importCounts;
}
function collectForbiddenPackageImports(projectRoot2, sourcePath, importCounts) {
  const relativePath = toProjectRelativePath(projectRoot2, sourcePath);
  const violations = [];
  for (const [packageName, count] of importCounts) {
    const replacement = FORBIDDEN_IMPORT_TARGETS.get(packageName);
    const importLabel = count === 1 ? "import" : "imports";
    violations.push(
      `${relativePath}: ${count} ${importLabel} from "${packageName}" -> migrate to ${replacement}`
    );
  }
  return violations;
}
function warnJsxTransform(projectRoot2, sourcePath, content) {
  if (!/\.[jt]sx$/.test(sourcePath) || !JSX_PATTERN.test(content)) {
    return;
  }
  const relativePath = toProjectRelativePath(projectRoot2, sourcePath);
  console.warn(
    `${formatWarningLabel()} JSX/TSX component trees in ${relativePath} will be transformed to React.createElement(...).`
  );
}
function scanSourceWarnings(projectRoot2) {
  const sourceRoot = path2.join(projectRoot2, "src");
  if (!existsSync2(sourceRoot)) {
    return [];
  }
  const violations = [];
  for (const sourcePath of collectSourceFiles(sourceRoot)) {
    const content = readFileSync2(sourcePath, "utf8");
    const importCounts = getForbiddenImportCounts(content);
    violations.push(
      ...collectForbiddenPackageImports(projectRoot2, sourcePath, importCounts)
    );
    warnJsxTransform(projectRoot2, sourcePath, content);
  }
  return violations;
}
function assertNoDirectSingletonImports(projectRoot2) {
  const violations = scanSourceWarnings(projectRoot2);
  if (violations.length === 0) {
    return;
  }
  throw new Error(
    [
      "Extensions must not import host-provided singleton dependencies directly.",
      'Found imports that must be migrated from "react" / "@chakra-ui/react" to the injected extension API:',
      ...violations.map((violation) => `- ${violation}`),
      `See ${HOST_PROVIDED_SINGLETON_DOCS}`
    ].join("\n")
  );
}

// ../../AppData/Roaming/npm/node_modules/create-sjmcl-extension/src/template-build/modules/singleton-analysis.js
function createNodeModulesPackagePattern(packageName) {
  return new RegExp(`(^|/)node_modules/${escapeRegExp(packageName)}(/|$)`);
}
function getImportParentMap(inputs) {
  const parentMap = /* @__PURE__ */ new Map();
  for (const [sourcePath, input] of Object.entries(inputs || {})) {
    for (const importedPath of (input.imports || []).map((item) => item.path)) {
      const normalizedImportedPath = normalizeRelativePath(importedPath);
      if (!normalizedImportedPath) {
        continue;
      }
      if (!parentMap.has(normalizedImportedPath)) {
        parentMap.set(normalizedImportedPath, /* @__PURE__ */ new Set());
      }
      parentMap.get(normalizedImportedPath).add(normalizeRelativePath(sourcePath));
    }
  }
  return parentMap;
}
function reconstructImportChain(startPath, childMap) {
  const chain = [normalizeRelativePath(startPath)];
  let currentPath = normalizeRelativePath(startPath);
  while (childMap.has(currentPath)) {
    currentPath = childMap.get(currentPath);
    chain.push(normalizeRelativePath(currentPath));
  }
  return chain;
}
function findImportChainToProjectSource(sourcePath, parentMap) {
  const queue = [normalizeRelativePath(sourcePath)];
  const visited = new Set(queue);
  const childMap = /* @__PURE__ */ new Map();
  while (queue.length > 0) {
    const currentPath = queue.shift();
    const parents = parentMap.get(currentPath);
    if (!parents) {
      continue;
    }
    for (const parentPath of parents) {
      if (visited.has(parentPath)) {
        continue;
      }
      visited.add(parentPath);
      childMap.set(parentPath, currentPath);
      if (!isNodeModulesPath(parentPath)) {
        return reconstructImportChain(parentPath, childMap);
      }
      queue.push(parentPath);
    }
  }
  return [normalizeRelativePath(sourcePath)];
}
function formatBytes(value) {
  return new Intl.NumberFormat("en-US").format(value || 0);
}
function getBundledBytesInOutput(metafile, packagePattern) {
  let bytes = 0;
  for (const output of Object.values(metafile?.outputs || {})) {
    for (const [inputPath, info] of Object.entries(output.inputs || {})) {
      if (packagePattern.test(normalizeRelativePath(inputPath))) {
        bytes += info.bytesInOutput || 0;
      }
    }
  }
  return bytes;
}
function warnBundledSingletonDependencies(metafile) {
  const inputs = metafile?.inputs || {};
  const parentMap = getImportParentMap(inputs);
  const warnings = [];
  for (const rule of HOST_SINGLETON_PACKAGES) {
    const packagePattern = createNodeModulesPackagePattern(rule.packageName);
    const bundledPaths = Object.keys(inputs).filter(
      (inputPath) => packagePattern.test(normalizeRelativePath(inputPath))
    );
    if (bundledPaths.length === 0) {
      continue;
    }
    const outputBytes = getBundledBytesInOutput(metafile, packagePattern);
    const exampleChains = [];
    for (const bundledPath of bundledPaths) {
      const trace = findImportChainToProjectSource(bundledPath, parentMap).join(" -> ");
      if (!exampleChains.includes(trace)) {
        exampleChains.push(trace);
      }
      if (exampleChains.length >= 3) {
        break;
      }
    }
    warnings.push(
      `${rule.packageName}: bundled ${bundledPaths.length} file(s), ${formatBytes(outputBytes)} byte(s) in output; prefer host singleton ${rule.replacement}.` + (exampleChains.length > 0 ? ` Dependency chain(s): ${exampleChains.join("; ")}` : "")
    );
  }
  if (warnings.length === 0) {
    return;
  }
  console.warn("");
  console.warn(
    `${formatWarningLabel()} Extension bundle contains host-provided singleton dependencies through third-party packages.`
  );
  console.warn(
    `${formatWarningLabel()} Direct imports from "react" / "@chakra-ui/react" are still forbidden, but transitive bundles only emit warnings so you can inspect the impact.`
  );
  for (const warning of warnings) {
    console.warn(`${formatWarningLabel()} - ${warning}`);
  }
  console.warn(`${formatWarningLabel()} See ${HOST_PROVIDED_SINGLETON_DOCS}`);
}

// ../../AppData/Roaming/npm/node_modules/create-sjmcl-extension/src/template-build/modules/build-options.js
import { Command, Option } from "commander";
function parseBooleanValue(rawValue, label) {
  const normalized = String(rawValue).trim().toLowerCase();
  if (["1", "true", "yes", "on"].includes(normalized)) {
    return true;
  }
  if (["0", "false", "no", "off"].includes(normalized)) {
    return false;
  }
  throw new Error(`${label} must be a boolean value.`);
}
function parseObfuscateValue(rawValue) {
  if (rawValue === void 0) {
    return true;
  }
  return parseBooleanValue(rawValue, "--obfuscate");
}
function createBuildOptionsProgram() {
  return new Command().name("build").helpOption(false).addOption(
    new Option("--mode <mode>", "Build mode").choices([
      "development",
      "production"
    ])
  ).addOption(
    new Option("--obfuscate [enabled]", "Enable identifier minification").argParser(parseObfuscateValue).default(void 0)
  ).allowUnknownOption(false).allowExcessArguments(false).exitOverride();
}
function parseBuildArguments(argv) {
  const program = createBuildOptionsProgram();
  try {
    program.parse(argv, { from: "user" });
  } catch (error) {
    if (error?.code?.startsWith("commander.")) {
      throw new Error(error.message.trim());
    }
    throw error;
  }
  const options = program.opts();
  return {
    mode: options.mode,
    obfuscate: options.obfuscate
  };
}
function resolveBuildOptions(argv) {
  const buildArguments = parseBuildArguments(argv);
  const buildMode = buildArguments.mode || "production";
  return {
    buildMode,
    obfuscate: buildArguments.obfuscate ?? buildMode === "production"
  };
}

// ../../AppData/Roaming/npm/node_modules/create-sjmcl-extension/src/template-build/modules/index.js
var __filename = fileURLToPath(import.meta.url);
var __dirname = path3.dirname(__filename);
var projectRoot = path3.resolve(__dirname, "..");
var manifestPath = path3.join(projectRoot, "sjmcl.ext.json");
var packagePath = path3.join(projectRoot, "package.json");
var distRoot = path3.join(projectRoot, "dist");
function createEsbuildOptions(sourceEntryPath, buildMode, obfuscate) {
  const shouldMinify = buildMode === "production";
  return {
    entryPoints: [sourceEntryPath],
    bundle: true,
    format: "iife",
    platform: "browser",
    target: ["es2015"],
    write: false,
    charset: "utf8",
    jsx: "transform",
    jsxFactory: "React.createElement",
    jsxFragment: "React.Fragment",
    define: {
      "process.env.NODE_ENV": JSON.stringify(buildMode)
    },
    metafile: true,
    minifySyntax: shouldMinify,
    minifyWhitespace: shouldMinify,
    minifyIdentifiers: obfuscate,
    logLevel: "info"
  };
}
async function main() {
  const manifest = readJson(manifestPath);
  const packageJson = readJson(packagePath);
  const sourceEntryPath = resolveSourceEntryPath(projectRoot);
  const { buildMode, obfuscate } = resolveBuildOptions(process.argv.slice(2));
  if (!IDENTIFIER_PATTERN.test(manifest.identifier || "")) {
    throw new Error("sjmcl.ext.json must contain a valid identifier.");
  }
  const frontendEntry = validateRelativePackagePath(
    manifest.frontend?.entry,
    "frontend.entry"
  );
  const version = manifest.version || packageJson.version;
  if (!semver.valid(version)) {
    throw new Error("A valid extension version is required in sjmcl.ext.json or package.json.");
  }
  const outputDirectory = path3.join(distRoot, manifest.identifier);
  const outputEntry = path3.join(outputDirectory, frontendEntry);
  const archivePath = path3.join(
    distRoot,
    `${manifest.identifier}-${version}.sjmclx`
  );
  rmSync(distRoot, { recursive: true, force: true });
  mkdirSync(path3.dirname(outputEntry), { recursive: true });
  assertNoDirectSingletonImports(projectRoot);
  const buildResult = await build(
    createEsbuildOptions(sourceEntryPath, buildMode, obfuscate)
  );
  warnBundledSingletonDependencies(buildResult.metafile);
  const outputFile = buildResult.outputFiles?.[0];
  if (!outputFile) {
    throw new Error("esbuild did not produce a bundled frontend script.");
  }
  const bundledScript = outputFile.text.replace(
    /^(?:\uFEFF)?(?:"use strict"|'use strict');\s*/,
    ""
  );
  writeFileSync(outputEntry, bundledScript);
  writeFileSync(
    path3.join(outputDirectory, "sjmcl.ext.json"),
    `${JSON.stringify(manifest, null, 2)}
`
  );
  copyIfExists(
    path3.join(projectRoot, "icon.png"),
    path3.join(outputDirectory, "icon.png")
  );
  copyIfExists(
    path3.join(projectRoot, "assets"),
    path3.join(outputDirectory, "assets")
  );
  copyIfExists(
    path3.join(projectRoot, "data"),
    path3.join(outputDirectory, "data")
  );
  const zipTree = {
    [manifest.identifier]: addDirectoryToZipTree(outputDirectory)
  };
  const archiveBuffer = zipSync(zipTree, { level: 9 });
  writeFileSync(archivePath, Buffer.from(archiveBuffer));
  console.log("");
  console.log(`Built ${outputDirectory}`);
  console.log(`Packed ${archivePath}`);
  if (packageJson.version !== version) {
    console.log(
      `Note: package.json version (${packageJson.version}) differs from sjmcl.ext.json version (${version}).`
    );
  }
}
main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`Build failed: ${message}`);
  process.exitCode = 1;
});
